### ISSUE TITLE
integration in liberation framework

### ISSUE THREAD

**Issue by cariocaITA** [KillahPotatoes/dubjunks-scripts#30]
i 've followed the instruction to insert this tools in a simple mission ... i'm going to insert this one in a liberation mission but i don't know how i merge the .xml file with the liberation's one.. could you tell me how can i make or could you insert in next liberation's release?

**Comment by Dubjunk** [comment]
Hey.
As you can see in this example https://community.bistudio.com/wiki/Stringtable.xml there are some seperators for different projects, packages, containers and so on.

You can just copy everything from `<Project name="KPDS">` to `</Project>` into the end of the lib stringtable.
For further support please join the Discord.
